find_file(scram_path "scram")
if(scram_path)
    execute_process(COMMAND scram tool info tensorflow-cc OUTPUT_VARIABLE SCRAM_TFCC_INFO)
    string(REGEX MATCH "\nINCLUDE=([^\n]*)" TFCC_STR ${SCRAM_TFCC_INFO})
    set(Tensorflow-cc_INCLUDE_DIRS "${CMAKE_MATCH_1}")
    string(REGEX MATCH "\nLIBDIR=([^\n]*)" TFCC_STR ${SCRAM_TFCC_INFO})
    set(Tensorflow-cc_LIBRARY_DIRS "${CMAKE_MATCH_1}")
    set(Tensorflow-cc_LIBRARIES "${Tensorflow-cc_LIBRARY_DIRS}/libtensorflow_cc.so")
endif()
