find_file(scram_path "scram")
if(scram_path)
    execute_process(COMMAND scram tool info tensorflow-c OUTPUT_VARIABLE SCRAM_TFC_INFO)
    string(REGEX MATCH "\nINCLUDE=([^\n]*)" TFC_STR ${SCRAM_TFC_INFO})
    set(APPEND Tensorflow-c_INCLUDE_DIRS "${CMAKE_MATCH_1}")
    string(REGEX MATCH "\nLIBDIR=([^\n]*)" TFC_STR ${SCRAM_TFC_INFO})
    set(Tensorflow-c_LIBRARY_DIRS "${CMAKE_MATCH_1}")
    set(Tensorflow-c_LIBRARIES "${CMAKE_MATCH_1}/libtensorflow.so")
endif()
