find_file(scram_path "scram")
if(scram_path)
    execute_process(COMMAND scram tool info protobuf OUTPUT_VARIABLE SCRAM_PB_INFO)
    string(REGEX MATCH "\nINCLUDE=([^\n]*)" PB_STR ${SCRAM_PB_INFO})
    set(Protobuf_INCLUDE_DIRS "${CMAKE_MATCH_1}")
    string(REGEX MATCH "\nLIBDIR=([^\n]*)" PB_STR ${SCRAM_PB_INFO})
    set(Protobuf_LIBRARY_DIRS "${CMAKE_MATCH_1}")
    set(Protobuf_LIBRARIES "${CMAKE_MATCH_1}/libprotobuf.so")
endif()
